version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: lms-server
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    volumes:
      - shared_data:/shared
      - server_logs:/app/logs
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: lms-client
    env_file:
      - ./client/.env
    ports:
      - "5173:5173"
    environment:
      - VITE_PORT=5173
    volumes:
      - shared_data:/shared
    depends_on:
      - server
    restart: unless-stopped

volumes:
  shared_data:
  server_logs:
